### ISSUE TITLE
Word count per locale

### ISSUE THREAD

**Issue by venkmanpeter** [resamsel/translatr#76]
For translators show how many words need to be translated per locale.

To do:
- [x] Add word_count to models message, key, locale, and project
- [x] Display word count in dashboard/projects, project, locales, keys
- [x] Update word count in project/locale/key/message when changing a message
- [x] Update word count in project/locale/key/message when deleting a message
- [x] Update word count in project/locale/key/message when importing/pushing messages
- [x] Allow updating the word count of a project manually by using a button

**Comment by resamsel** [comment]
This issue has been split up into locale word count (#76) and reporting (#78).
